### ISSUE TITLE
Refactor Code (Into 2-3 Swift files)

### ISSUE THREAD

**Issue by tedbarnett** [tedbarnett/Boswell#14]
- clean up code to eliminate unclear, messy, or poorly implemented code
- Update to latest Swift 5-style code
- if possible, break ViewController.swift into 2-3 smaller files. We want to keep using ChatGPT-4 for code advice but we can no longer paste all of ViewController.swift into the web client!

**Comment by tedbarnett** [comment]
What did you do here?  Quick comment explaining would be helpful.

**Comment by bhautikpatoliya004** [comment]
Yes, sure I will add my comments on it. Basically, I have split ViewController.swift file into 3 pieces. 
1. Timer: It will handle showing a popup after 8 seconds
2. AVSpeechSynthesizerDelegate: It will handle all delegates of AVSpeechSynthesizer
3. Main class: It contains the whole life cycle of the class

Also, I've created 3 separate files for clean code.

1. APIManager.swift
I have added a separate class for REST API calls. So that all network calls will be separated and the same way I have done ShareManager which will handle all shared code.

2. Extension.swift
This file is responsible to separate all utility extensions like UIColor, NSAttributedString, etc.

3. Constant.swift 
This file is responsible to declare constants for the app like string constants.
