### ISSUE TITLE
Create "My Profile" Menu Item for birthday, name

### ISSUE THREAD

**Issue by tedbarnett** [tedbarnett/Boswell#55]
Create a new Menu Item called "My Profile" that brings up a dialog box asking:

- My first name (text field)
- My date of birth (with same date-selection UI)

If either of those items is not filled-in by the user, ask the user for them whenever the Boswell mode is selected.  If they are already filled in, do not ask the user for them when Boswell is selected: just switch to Boswell mode.

To make use of the first name.  We will need to send an invisible prompt to OpenAI with "Please refer to me as {firstname]" and also ignore what it sends back.  I think it's worth building a function for that (which sends a prompt to OpenAI and ignores the response).

**Comment by bhautikpatoliya004** [comment]
@tedbarnett  I think instead of sending an invisible prompt we need to mention in this text

"Please refer to me as \(firstname). I want you to interview me about my life. Please use my name while taking an interview. I want you to start by stating that when I was 13 years old, the year was \(year + 13) and briefly mention 3 major world events that occurred that year. Then stop, skip two single blank lines, and then ask me a question about my life when I was 13 years old. Wait for me to type in an answer then ask another question that encourages me to tell more about my life. Stop after you've asked each question to wait for me to answer. If I ever respond with the word QUIT, then stop the interviewing process and return to answering questions as ChatGPT would." 

What's your thought on it? If the above text is not proper then please rewrite it for me. I will update it.

**Comment by tedbarnett** [comment]
I think you've got the prompt text right!

**Comment by tedbarnett** [comment]
When I go to edit my profile and enter my name, the onscreen keyboard blocks my view of the buttons so I cannot exit the dialog. Maybe keyboard should vanish when I press Enter after typing in my name?

**Comment by tedbarnett** [comment]
![IMG_5685](https://user-images.githubusercontent.com/694013/235231163-2a2aa7fb-f52b-4f83-be5c-eebcc5f27f8a.PNG)

That's the screen situation: can't finish the dialog box!

**Comment by tedbarnett** [comment]
If the user has not entered a name, just let [Name] = "" so that it says "Hello..." rather than "Hello [Name]".  Currently, the app seems to refer to me as "ChatGPT" if I have not filled in a name.  This causes a problem because it then thinks that it's talking to itself!
