### ISSUE TITLE
Save Audio Files from Boswell Interviews

### ISSUE THREAD

**Issue by tedbarnett** [tedbarnett/Boswell#92]
Since this is really starting to work well, I don't want to lose the audio interviews we are creating. I'm still thinking about the ideal interface for this, but the goal is to save any audio interview files so that they can be shared with family and friends later.

So., when the user chooses "New Chat" in Boswell mode:
1. clear the chat history (see Issue #91 )
2. save a copy of the latest audio interview as a .mp3 file with the name format "Ted Interview - 2023-05-10 12.53pm.mp3" (i.e. "{name} Interview - YYYY-MM-DD HH.MM{pm/am}.mp3") in a "Boswell" folder on iCloud.  If that's too hard for now, can we save it on the phone somewhere?

I know that you should not use the colon character (":")  in Mac/iOS filenames, so I'm using a "." for the HH:mm delimiter.

This folder can be hidden from the user for now: we will figure out how to make it accessible later.

**Comment by bhautikpatoliya004** [comment]
@tedbarnett  I'm using .m4a format because in iOS AVAudioRecorder doesn't support directly recording audio in .mp3 format. It only supports recording to linear PCM (.caf), MPEG-4 AAC (.m4a), and Apple Lossless (.m4a) formats. 

When the user speaks I'm recording the user's voice using AVAudioRecorder and when the AI responds by speaking I'm writing it on the audio buffer in .m4a format.

supported output files.
com.apple.quicktime-movie (.mov)
com.apple.m4a-audio (.m4a)
public.mpeg-4 (.mp4)
com.apple.m4v-video (.m4v)
org.3gpp.adaptive-multi-rate-audio (.amr)
com.microsoft.waveform-audio (.wav)
public.aiff-audio (.aiff)
public.aifc-audio (.aifc)
com.apple.coreaudio-format (.caf)

**Comment by bhautikpatoliya004** [comment]
@tedbarnett  I have written each audio interview in the Boswell folder. But it's not visible to the user. I'm thinking about where can we show this list of audio files.

my suggestion is to when the user tap on "Play Interview Audio" opens a new screen and shows the list of recorded audio from the Boswell folder. Users can play any audio from the list. let me know your thoughts on it.

**Comment by tedbarnett** [comment]
Okay. Let’s leave it in m4a for now. I’ll check where that might cause issues (eg if sent to a friend on Android or Windows?), but these days most formats are supported. I like the “play from list” idea. Can we make that list compact (like a pop-up list maybe) so the screen is not too cluttered?

---
***@***.***
https://www.linkedin.com/in/tedbarnett

**Comment by tedbarnett** [comment]
See #106 for where this is going.  Ideally, the items in the pop-up list would correspond to "topics" the user has been interviewed about (e.g. "1984" and all of the answers that followed the first prompt).

**Comment by tedbarnett** [comment]
I like the "play from list" idea when you are ready to implement it in the Audio Interview window.
